#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("monCarousel.Resource", IsApplication=true)]

namespace monCarousel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int _photo0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int _photo1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int _photo2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int _photo3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int _photo4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int photo0 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int photo1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int photo2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int photo3 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int photo4 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Pphoto0 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Pphoto1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Pphoto2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Pphoto3 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Pphoto4 = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int myImage = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int myLinµLayout = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int myViewpager = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int myFragment = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
